#################################################################
## Groups
#################################################################

Household:
  - person.joe_swantek
  - person.lisa_swantek
